server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml # Promtail uses this to track how much of a file it has read

clients:
  - url: http://loki:3100/loki/api/v1/push # This is how Promtail sends logs to Loki

scrape_configs:
  - job_name: django_app_logs1
    static_configs:
      - targets:
          - localhost
        labels:
          job: django_app_logs1
          __path__: /var/log/django/django1.log # This is the exact path to your log file inside the shared volume
          container: django-project1 # Custom label for your Django app container