global:
  resolve_timeout: 40s

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 20s
  repeat_interval: 30s
  receiver: 'slack-notifications'

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - channel: '#test-uptime-kuma'
        api_url: 'https://hooks.slack.com/services/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'
        send_resolved: true
        title: '{{ .CommonLabels.alertname }}'
        text: >
          {{ range .Alerts }}
            *Alert:* {{ .Annotations.summary }}
            *Description:* {{ .Annotations.description }}
            *Severity:* {{ .Labels.severity }}
            *Instance:* {{ .Labels.instance }}
            *Status:* {{ .Status }}
          {{ end }}
