auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9095

common:
  path_prefix: /loki
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2020-10-24
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

compactor:
  working_directory: /loki/compactor

limits_config:
  retention_period: 720h # Example: retain logs for 30 days (720 hours)
  reject_old_samples: true
  reject_old_samples_max_age: 168h # Logs older than this will be rejected on ingestion
  max_query_lookback: 720h # This is the main parameter for query lookback in 3.x

# The chunk_store_config section (and max_look_back_period) is removed or implicitly handled in 3.x.
# Remove it completely.

table_manager:
  retention_deletes_enabled: true
  retention_period: 720h # This is the primary retention setting for the table manager